import './globals.css';
import NavBar from './componets/NavBar';
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NavBar />
        {children}
      </body>
    </html>
  )
}
