import './globals.css';
import NavBar from './componets/NavBar';
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1437656432973757"
       crossorigin="anonymous"></script>
      </head>
      <body>
      <NavBar />
        {children}
      </body>
    </html>
  )
}
